### ISSUE TITLE
Help with watchMnist() redux-saga watcher function

### ISSUE THREAD

**Issue by PranjalAgni** [ixartz/handwritten-digit-recognition-tensorflowjs#10]
I was going through the code-base and found this redux-saga function interesting.

I have generally seen watcher function using `takeLatest()` or `takeEvery()`, but here you used `call()` can you please explain how this is working.

https://github.com/ixartz/handwritten-digit-recognition-tensorflowjs/blob/20864a2b544a547b8e8a4a961f12b9f5af89b584/src/sagas/mnist.js#L83-L86

Thanks ✨

**Comment by ixartz** [comment]
As you said takeLatest and takeEvery are used for watcher. But, call() are used for calling a function. In your example yield call(request ....) called this function : https://github.com/ixartz/handwritten-digit-recognition-tensorflowjs/blob/20864a2b544a547b8e8a4a961f12b9f5af89b584/src/sagas/mnist.js#L52

The first parameter of call() is the function you want to call.
The second parameter of call() is the first parameter of the function you want to invoke. In our example, the first parameter of the request function : pretrainedHandwritingDigitsClassifier

So the use case are totally different between take* and call()

**Comment by PranjalAgni** [comment]
Thanks got it `request()` gets suspended and watches for the two actions you have written in it.
